#!/bin/bash

yum update -y
yum install krb5-workstation -y
yum install pam_krb5 -y
yum install epel-release -y
# clam packages installed by MailScanner:
#yum install clamav -y
#yum install clamav-update -y
#yum install clamav-scanner-systemd -y
yum install git -y

yum install postfix -y
yum install dovecot -y

# Set up vmail environment
useradd -c 'Virtual Mail' -d /home/vmail -u 1002 -s /sbin/nologin -U vmail
echo "fs-6b7abca2.efs.eu-west-1.amazonaws.com:/ /home/vmail nfs nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 0 0" >> /etc/fstab
mount -a

# Install MailScanner:
curl https://s3.amazonaws.com/msv5/release/MailScanner-5.0.3-7.rhel.tar.gz > MailScanner-5.0.3-7.rhel.tar.gz
tar -zxvf MailScanner-5.0.3-7.rhel.tar.gz
printf '\n2\nY\nY\nY\nY\nY\nY\nY\n0\n' | MailScanner-5.0.3-7/install.sh

