#!/bin/bash

yum update -y
yum install krb5-workstation -y
yum install pam_krb5 -y
yum install epel-release -y
# clam packages installed by MailScanner:
#yum install clamav -y
#yum install clamav-update -y
#yum install clamav-scanner-systemd -y
yum install git -y

yum install postfix -y
yum install dovecot -y

# Set up vmail environment
useradd -c 'Virtual Mail' -d /home/vmail -u 1002 -s /sbin/nologin -U vmail
echo "fs-6b7abca2.efs.eu-west-1.amazonaws.com:/ /home/vmail nfs nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 0 0" >> /etc/fstab
mount -a

# Install MailScanner:
curl https://s3.amazonaws.com/msv5/release/MailScanner-5.0.3-7.rhel.tar.gz > MailScanner-5.0.3-7.rhel.tar.gz
tar -zxvf MailScanner-5.0.3-7.rhel.tar.gz
printf '\n2\nY\nY\nY\nY\nY\nY\nY\n0\n' | MailScanner-5.0.3-7/install.sh

# Install certbot:
git clone https://github.com/certbot/certbot /opt/certbot
# Get cert:
#
### NEED TO ENSURE DNS ENTRY DONE FIRST.  NEED TO USE STATIC EIP FOR REVERSE DNS, SO ASSOCIATE EIP WITH THIS NEW HOST BEFORE THIS LINE
/opt/certbot/certbot-auto -n --os-packages-only
/opt/certbot/certbot-auto certonly -n --agree-tos --rsa-key-size 4096 --renew-by-default -m tony@mulini.org --standalone -d mailhub.mulini.net --test-cert
# Various fixes:

